### ISSUE TITLE
Performance and approach

### ISSUE THREAD

**Issue by guilhermeaiolfi** [middlewares/image-manipulation#2]
Hi,

I was trying to do the same thing, even the JWT library  I've chosen is the same. Except I am using intervention/image library to create the images. But I am a bit skeptical about de approach since I have seen almost nobody else doing the same. Do you know why is that? Is there any big performance hit doing it?

From what I could gather, SHA256 is a pretty fast algorithm and shouldn't be a problem. I am also researching a different encrypt method to simply the URL, kinda of:

```php
$encrypted = openssl_encrypt($data, 'aes-128-cbc-hmac-sha256', $key);
$encrypted = base64_encode($encrypted);
```

Anyway, just reaching out to discuss it further and see your thoughts.

**Comment by guilhermeaiolfi** [comment]
I've test the performance of my idea using openssl_encrypt directly and it keeps 0.78~0.80s to 100.000 encrypts in my machine. That's good enough. I'll try the jwt latter to see how it performs. For the openssl_encrypt I used the example #2 in the php openssl_encrypt documentation: https://www.php.net/manual/en/function.openssl-encrypt.php.

I tried around 15 methods available in the list I got by the command: ```openssl_get_cipher_methods()```, No difference at all between them.

**Comment by oscarotero** [comment]
I'm using this approach in several projects ([this](https://historia-arte.com/), for example) without any problem. In my case, I don't worry about performance (although it should be pretty fast) because the result is saved in a file in a public directory, so the conversion is done only in the first request, next requests return the image as a static file by the server, without being processed by php.

**Comment by guilhermeaiolfi** [comment]
How exactly that works? The server forward the request to the middleware because the image don't exist. Then the middleware creates the image. Because of that, now that the image is there in the filesystem, the server returns it. Is that so?

Just to registered here for the future curious yes, using openssl_encrypt is about 3x faster than using the library in php 7.4.10.

Well, that mean, if you manage to put 1000 images in a single page, it will take just 0,003s to process that chunk.

**Comment by guilhermeaiolfi** [comment]
I manage to do the way I describe just before. I just don't see how eliminate the `getUri()` calls. And since all images would be in the root of that public directory, it could potencially slow down things (some filesystems take a hit when there are a big number of entries in just one folder).

**Comment by oscarotero** [comment]
Yes, In my nginx server I have something like this:

```
location ~* \.(?:jpg|jpeg|gif|png|webp)$ {
    try_files $uri $uri/ /index.php;
}
```

So, if the file does not exists, the request is handled by php and the middlewares. Something like that can be done also with apache and other servers.

And about the folders, this middleware generate different folders [by spliting the jwt value](https://github.com/middlewares/image-manipulation/blob/master/src/ImageManipulation.php#L75). So, for example the value:

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydGlzdFwvaW1hZ2VGaWxlXC9qZWFuLWZyYW5jM2E3b2lzX21pbGxldC1hdXRvcG9ydHJhaXQuanBnIiwicmVzaXplQ3JvcCw1MCw1MCJdfQ.INBgeeJpqDvtmP1tyb2J-bbVUIp9i4ENJGIEzj9Y8Kk.jpg
```
Is converted to

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbSI6WyJcL2FydGlzdFwvaW1hZ2VGaWxlXC9qZWFuLWZyYW5jM2E3b2lzX21pbGxldC1hdXRvcG9ydHJhaXQuanBnIiwicmVzaXplQ3JvcCw1MCw1MCJdfQ.INBgeeJpqDvtmP1tyb2J-bbVUIp9i4ENJGIEzj9Y/8Kk.jpg
```
(Note the `/` at the end)

**Comment by guilhermeaiolfi** [comment]
Thank for the info. But just to be clear, the getUri() is still needed, right?

**Comment by oscarotero** [comment]
Yes, it's needed to generate the urls in the php templates.

**Comment by guilhermeaiolfi** [comment]
Ahh, ok. That was the part I was benchmarking. It worked fine for me, it is
faster and you could remove the jwt dependency. I guess it would be faster
to decrypt too, but I will have to confirm that.

You can close the issue if you want to. Thanks for the info.

Em qui, 15 de out de 2020 18:03, Oscar Otero <notifications@github.com>
escreveu:
